'use client';

import { Card, CardContent, Skeleton } from '@visionops/ui';
import { formatDateTime } from '@visionops/utils';
import { useEvents } from '@/features/events/hooks';
import { eventLabel } from '@/features/events/types';
import { SeverityBadge, StatusBadge } from '@/features/events/severity';

export default function EventsPage() {
  const { data: events, isLoading } = useEvents();

  return (
    <div className="mx-auto max-w-4xl px-8 py-10">
      <div className="mb-6">
        <h1 className="text-2xl font-semibold tracking-tight">AI events</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Business events generated by the rule engine.
        </p>
      </div>

      {isLoading && <Skeleton className="h-24" />}
      {!isLoading && events?.length === 0 && (
        <Card>
          <CardContent className="py-10 text-center text-sm text-muted-foreground">
            No events yet.
          </CardContent>
        </Card>
      )}
      {!isLoading && events && events.length > 0 && (
        <div className="space-y-2">
          {events.map((event) => (
            <Card key={event.id}>
              <CardContent className="flex items-center justify-between py-3">
                <div className="flex items-center gap-3">
                  <SeverityBadge severity={event.severity} />
                  <div>
                    <p className="text-sm font-medium">{eventLabel(event.event_type)}</p>
                    <p className="text-xs text-muted-foreground">
                      {formatDateTime(event.started_at)}
                      {event.duration_seconds != null && ` · ${event.duration_seconds}s`}
                    </p>
                  </div>
                </div>
                <StatusBadge status={event.status} />
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
