"""PDF rendering for reports (reportlab).

Produces a clean, branded, business-readable PDF: header (+ optional logo),
executive summary, KPIs, alert + camera tables, recommendations, with page
numbers and a generation timestamp.
"""

from __future__ import annotations

import io

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.schemas.report import ReportData

_ACCENT = colors.HexColor("#4f46e5")


def _footer(canvas, doc) -> None:
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)
    canvas.drawString(20 * mm, 12 * mm, "Generated by VisionOps AI")
    canvas.drawRightString(190 * mm, 12 * mm, f"Page {doc.page}")
    canvas.restoreState()


def _kpi_table(data: ReportData) -> Table:
    rows = [
        ["Total footfall", str(data.total_footfall), "Avg occupancy", str(data.avg_occupancy)],
        ["Peak occupancy", str(data.peak_occupancy), "Avg queue", str(data.queue_stats.avg_queue_length)],
        ["Total alerts", str(data.total_alerts), "Critical alerts", str(data.critical_alerts)],
        ["Cameras online", f"{data.cameras_online}/{data.total_cameras}", "Uptime", f"{data.overall_uptime_pct}%"],
    ]
    t = Table(rows, colWidths=[40 * mm, 45 * mm, 40 * mm, 45 * mm])
    t.setStyle(
        TableStyle(
            [
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("TEXTCOLOR", (0, 0), (0, -1), colors.grey),
                ("TEXTCOLOR", (2, 0), (2, -1), colors.grey),
                ("FONTNAME", (1, 0), (1, -1), "Helvetica-Bold"),
                ("FONTNAME", (3, 0), (3, -1), "Helvetica-Bold"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("LINEBELOW", (0, 0), (-1, -1), 0.25, colors.lightgrey),
            ]
        )
    )
    return t


def _table(header: list[str], rows: list[list[str]], widths: list[float]) -> Table:
    data = [header, *rows] if rows else [header, ["—"] * len(header)]
    t = Table(data, colWidths=widths, repeatRows=1)
    t.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), _ACCENT),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f7")]),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ]
        )
    )
    return t


def build_report_pdf(data: ReportData, *, logo_bytes: bytes | None = None) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=20 * mm, bottomMargin=20 * mm)
    styles = getSampleStyleSheet()
    title = styles["Title"]
    h2 = styles["Heading2"]
    body = styles["BodyText"]
    elements: list = []

    if logo_bytes:
        try:
            elements.append(Image(io.BytesIO(logo_bytes), width=30 * mm, height=30 * mm))
        except Exception:  # noqa: BLE001 - a bad logo must not break the PDF
            pass

    elements.append(Paragraph(f"{data.company_name} — {data.report_type.title()} Report", title))
    elements.append(
        Paragraph(
            f"Period: {data.start_date} to {data.end_date} · "
            f"Generated {data.generated_at:%Y-%m-%d %H:%M UTC}",
            body,
        )
    )
    elements.append(Spacer(1, 8 * mm))

    elements.append(Paragraph("Executive Summary", h2))
    for bullet in data.executive_summary:
        elements.append(Paragraph(f"• {bullet}", body))
    elements.append(Spacer(1, 6 * mm))

    elements.append(Paragraph("KPI Overview", h2))
    elements.append(_kpi_table(data))
    elements.append(Spacer(1, 6 * mm))

    elements.append(Paragraph("Alerts", h2))
    elements.append(
        _table(
            ["Time", "Camera", "Event", "Severity", "Status"],
            [
                [f"{r.time:%m-%d %H:%M}", r.camera_name, r.event_type, r.severity, r.status]
                for r in data.alert_rows
            ],
            [28 * mm, 40 * mm, 55 * mm, 22 * mm, 25 * mm],
        )
    )
    elements.append(Spacer(1, 6 * mm))

    elements.append(Paragraph("Cameras", h2))
    elements.append(
        _table(
            ["Camera", "Status", "Uptime", "Footfall", "Alerts"],
            [
                [c.camera_name, c.status, f"{c.uptime_pct}%", str(c.total_footfall), str(c.total_events)]
                for c in data.cameras
            ],
            [55 * mm, 25 * mm, 25 * mm, 30 * mm, 25 * mm],
        )
    )
    elements.append(Spacer(1, 6 * mm))

    elements.append(Paragraph("Recommendations", h2))
    for rec in data.recommendations:
        elements.append(Paragraph(f"• {rec}", body))

    doc.build(elements, onFirstPage=_footer, onLaterPages=_footer)
    return buffer.getvalue()
